spec:
  inputs:
    version_type:
      type: string
      default: 'minor'
    runner_tags:
      type: string
      default: 'docker'

---
stages:
  - prepare
  - trigger
  - publish
  - release

include:
  - project: coding/homelab/gitlab-ci-templates
    ref: main
    file: templates/pipelines/default.yml
    inputs:
      version_type: $[[ inputs.version_type ]]
      runner_tags: $[[ inputs.runner_tags ]]

variables:
  TP_PREPARE_SCRIPT_REF: main
  TP_PREPARE_SCRIPT_REF_TYPE: branch

  # job trigger
  TP_RUN_PUBLISH: "true"
  TP_RUN_RELEASE: "true"

  # publish
  TP_PUBLISH_TYPE: dind_socket
  # publish to harbor and Dockerhub
  TP_PUBLISH_DOCKER_REGISTRIES: $DF_PUBLISH_DOCKER_REGISTRIES
  TP_PUBLISH_DOCKER_REGISTRY_USERNAMES: $DF_PUBLISH_DOCKER_REGISTRY_USERNAMES
  TP_PUBLISH_DOCKER_REGISTRY_PASSWORDS: $DF_PUBLISH_DOCKER_REGISTRY_PASSWORDS
  TP_PUBLISH_DOCKER_BUILD_IMAGE_NAMESPACES: $DF_PUBLISH_DOCKER_BUILD_IMAGE_NAMESPACES
  TP_PUBLISH_DOCKER_BUILD_CONTEXT_DIR: .
  TP_PUBLISH_DOCKER_DOCKERFILE: ./Dockerfile
  TP_PUBLISH_DOCKER_BUILD_IMAGE_REPOSITORY: $CI_PROJECT_NAME
  TP_PUBLISH_DOCKER_BUILD_ARGS: "BUILD_DATE=$CI_PIPELINE_CREATED_AT,VCS_REF=$CI_COMMIT_SHORT_SHA,VERSION=$CI_COMMIT_REF_NAME"

  # release
  TP_RELEASE_TYPE: 'curl'
  TP_RELEASE_TAG_PREFIX: v
  TP_RELEASE_TAG_SEARCH: $TP_RELEASE_TAG_PREFIX
